redis:
  image: redis
  ports:
    - "6379:6379"

roshi:
  image: "500px/roshi:latest"
  links:
    - redis
  command: "-redis.instances=redis:6379"

streams:
  image: "ello/streams"
  links:
    - roshi
  environment:
    PORT: "8080"
    ROSHI_URL: "http://roshi:6302"
  ports: 
    - "8080:8080"
